### ISSUE TITLE
Rancher needs to be accommodated somehow

### ISSUE THREAD

**Issue by kvanderveer** [SUSE-Enceladus/public-cloud-info-client-ui#5]
We now make Rancher available in the public cloud. https://aws.amazon.com/marketplace/pp/prodview-2yzbnvagmi4as.
While pint was originally designed to allow customers to install old versions of VMs, the name implies it is the definitive place where SUSE products in the public cloud can be found. So what do we do with Rancher? Maybe just a link, or clarify the use cases for the site, or both.

**Comment by rjschwei** [comment]
> While pint was originally designed to allow customers to install old versions of VMs

There is no "install" of old VMs. Images in the Public Cloud are used to launch instances. Further the idea behind pint was for users to be able to find the latest published images, find images published by SUSE, and find successor images.

Further it is known that the current listing is transitory. The goal is to have a curated install either via an image that follows the ideas around https://github.com/SUSE-Enceladus/blue-horizon or via CFN/Quick Start. At this point the listing of the Rancher Management Product goes away as the product will be pulled in via helm chart and the listing we will have is either a temporary installer VM or a Quick Start.

The question is the value we would bring by listing something that is transitory and is expected to be obsoleted in 3 or 4 months. Additionally what we are actually providing is a helm chart which has a specific link in the registry, such as  709825985650.dkr.ecr.us-east-1.amazonaws.com/suse/rancher. The pint (https://github.com/SUSE-Enceladus/public-cloud-info-service) data source has no provisions for such information as the data structures for pint were designed and implemented with focus on VM images. Last but not least the data in pint is designed and implemented to provide information to use the listing with the command line tools, in AWS that is the ami-id and region to use the product with the aws cli. This does not apply in this case.
